baseURL = "https://ammaiaecoforest.github.io/"
title = "Ammaia Ecoforest Cikupa"
languageCode = "en-us"
theme = "Raditian"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Lokasi & Fasilitas"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Lokasi & Fasilitas"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]
  title = "Ammaia Ecoforest Cikupa"
  description = "Perumahan baru Astra Land di Cikupa Suvarna Sutera. Launching cluster Lavatera harga jual rumah Rp. 1,6 milyaran*"
  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Ammaia"
    text2 = "Ecoforest"

  [params.footer]
      copyright = "© Ammaia Ecoforest 2023. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"